### ISSUE TITLE
How to customize the build folder?

### ISSUE THREAD

**Issue by ooker777** [lumeland/theme-simple-wiki#10]
For mysterious reason GitHub Page doesn't recognize folders whose names have a dash at the beginning. Therefore it cannot read `_site`. Is there a way to customize the build folder?

**Comment by oscarotero** [comment]
Github Pages are published in a subdirectory, like `https://username.github.io/repository/`.
You have to specify the final location of your site, and the theme automatically modifies all links to insert the `/repository` folder at the beginning of the URL.

For example:

```js
const site = lume({
    location: new URL("https://username.github.io/repository"),
});

site.use(wiki());

export site;
```

Alternatively, you can pass the location to the build script:

```
deno task build --location=https://username.github.io/repository
```

**Comment by ooker777** [comment]
I'm not sure how that will solve the problem? I follow your advice and it doesn't work. Can you take a look at [this repo](https://github.com/QuaCau-TheSphere/GW-vat-ly-an-du-trong-triet-hoc) and tell me what's wrong? The `_config.ts` file:
```js
import lume from "lume/mod.ts";
import wiki from "wiki/mod.ts";

const site = lume({
  location: new URL("https://quacau-thesphere.github.io/GW-vat-ly-an-du-trong-triet-hoc"),
});

site.use(wiki());

export default site;
```

**Comment by oscarotero** [comment]
Ups, sorry. I misunderstood your initial comment.
Yes, GitHub ignores the folders starting with `_` (I think it's inherited from Jekyll).

The best way to use GitHub pages is using the GitHub Actions method. You have the complete instructions here: https://lume.land/docs/advanced/deployment/#github-pages

**Comment by ooker777** [comment]
I didn't know that page, thanks. You can also [bypassing Jekyll on GitHub Pages](https://github.blog/news-insights/bypassing-jekyll-on-github-pages/ "Bypassing Jekyll on GitHub Pages - The GitHub Blog") by having a `.nojekyll` file at the root.

Still, I wonder why Lume picks the `_site` as the build folder? Can I change it?
