### ISSUE TITLE
Clicking on root menu item opens new page instead of expanding/collapsing

### ISSUE THREAD

**Issue by thdoan** [lumeland/theme-simple-wiki#11]
When I click on menu item 1 in screenshot, I expected the menu to expand/collapse just as it does when I click on menu item 2, but instead it goes to another page. It would be nice for the default behavior to be consistent with menu item 2 where it toggles the menu group instead of navigating to a different page.

![image](https://github.com/user-attachments/assets/0a2e49a3-2ecc-49a1-aac0-148c3eadebaf)

**Comment by oscarotero** [comment]
The behavior depends on whether the folder has a index.html file or not.
Due the page `/folder/index.html` exists, it's opened when clicking the "folder" menu item. But there's no `folder/other-folder/index.html`, so this option has not a link to any page.

Note that you can click on the caret icon to open/close the options without open the page.

**Comment by thdoan** [comment]
Thanks for the info.
