### ISSUE TITLE
Mobile friendly

### ISSUE THREAD

**Issue by RickCogley** [lumeland/theme-simple-wiki#4]
Thank you for this theme. At present, the side menu is simply on the left no matter what the viewport size is, but it would be great if some day, this theme could be more responsive, so that you don't have to zoom into the main content on mobile.

**Comment by oscarotero** [comment]
Oops, thanks for bringing this up! I just realized the meta viewport is missing.

**Comment by RickCogley** [comment]
Indeed it is. Trying adding it now. Also: `<meta charset="utf-8">` would be good

**Comment by RickCogley** [comment]
Yep, that worked to fix it. 

<img width="890" alt="image" src="https://github.com/lumeland/theme-simple-wiki/assets/512328/d6f41a87-1453-4001-9fa3-4261fe46a1bc">

**Comment by oscarotero** [comment]
fixed in v0.6.1
