### ISSUE TITLE
[Feature request] Ability to collapse/expand tree nodes

### ISSUE THREAD

**Issue by thdoan** [lumeland/theme-simple-wiki#9]
It would be nice if this theme can have collapsible sections like on https://lume.land/docs/overview/about-lume/

**Comment by oscarotero** [comment]
It's a godd idea. I'll work on that.

**Comment by ooker777** [comment]
I wonder why you didn't implement it sooner? I suppose it's a basic feature and the code should be easy?

**Comment by oscarotero** [comment]
The lateral menu is now collapsible. Example: https://vento.js.org/
